config/routes.rb
Rails.application.routes.draw do
  root to: 'gossips#index', as: :home
  devise_for :moussaillons
  resources :gossips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :content, presence: true
  belongs_to :moussaillon
end

app/models/moussaillon.rb
class Moussaillon < ApplicationRecord
  attr_accessor :sign_up_code
  validates :sign_up_code, on: :create, presence: true, inclusion: { in: ["GossipTeam2018"] }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true, with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :sign_up_code])
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def new
    if moussaillon_signed_in?
      @gossip = Gossip.new
      render 'new'
    else
      redirect_to home_path
    end
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.moussaillon_id = current_moussaillon.id
    if @gossip.save
      flash[:success] = "Votre gossip a bien été envoyé sur la toile"
      redirect_to home_path
    else
      flash[:warning] = "Pour bitcher il faut écrire quelque chose sinon quel intérêt ?"
      render 'new'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to home_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/index.html.erb
<% if moussaillon_signed_in? %>
<h2>Du frais, du beau et on en redemande !</h2>
  <h4>Nos membres sont particulièrement inspirés.. je suis sûr que vous trouverez quelques perles qui vous plairont ! </h4>
  <%= link_to("Je veux bitcher", new_gossip_path , class: "btn btn-info") %>

  <hr>

  <h4 class="index">Les gossips</h4>
    <div class="list">
      <% @gossips.each do |gossip| %>
      <div class="line">
        <div class="cell">
       <q><%= gossip.content.capitalize %></q>
       </div>
       <div class="cell">
        <%= Moussaillon.find_by(id: gossip.moussaillon_id).username %>
      </div>
        <div class="cell">
        Le <%= gossip.created_at.strftime("%d %b. %Y")  %>
        à <%= gossip.created_at.strftime("%H:%M") %>
        <% @id = gossip.id  %>
        </div>
        <div class="cell">
        <% if gossip.moussaillon_id == current_moussaillon.id %>
          <span class="delete"><%= link_to("Supprimer", "gossips/#{@id}", method: :delete) %> </span><br>
          <% end %>
          </div>
          </div>
      <% end %>
    </div>
<% else %>
<h2>C'est le moment de bitcher..</h2>
  <h4>Mais pour cela il faut te <%= link_to("connecter", new_moussaillon_registration_path) %> ou <%= link_to("t'inscrire", new_moussaillon_session_path) %>..</h4>
  <p>..viens me susurrer à l'oreille, je sens que je vais adorer ça !</p>

<% end %>

app/views/gossips/new.html.erb
<h2>Toi aussi, écris ton gossip !</h2>

<h4>Tapes ici ce que tu veux nous dire de si brûlant :</h4>

<%= form_for @gossip, url: {action: 'create'} do |f| %>
  <%= f.text_area :content, size: "70x5" %> <br><br>
  <%= f.submit "Bitcher", class: "btn btn-lg btn-info"  %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light rounded" style="background-color: #7DDAD8">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= home_path %>">Gossips<span class="sr-only">(current)</span></a>
      </li>
      <% if moussaillon_signed_in? %>
        <li class="nav-item">
          <a class="nav-link disabled" href="<%= new_gossip_path %>">Nouveau gossip</a>
        </li>
        <li class="nav-item">
        <span class="nav-link disabled">
          <%= link_to "Me déconnecter",  destroy_moussaillon_session_path, method: :delete  %>
        </span>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link disabled" href="<%= new_moussaillon_registration_path %>">S'inscrire</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="<%= new_moussaillon_session_path %>">Se connecter</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header'  %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/moussaillons/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>